name: Run Tests
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install update
        run: sudo apt update -y
      - name: Install dependencies
        run: sudo apt install nginx -y
      - name: Run tests
        run: sudo systemctl start nginx
